namespace Cobweb{
    public enum TokenType
    {
       ID, NUMBER, MINUS,PLUS,DIVIDE,MULTIPLY,ARROW,BOOLEQ,BOOLNOTEQ,NOT,SQUARE_OPEN,SQUARE_CLOSE,BRACE_OPEN, BRACE_CLOSE,BOOLMORE,BOOLLESS,BOOLLESSEQ,BOOLMOREEQ,STRING,COMMA,END_OF_FILE
    }
}